### ISSUE TITLE
how to build libomnishare?

### ISSUE THREAD

**Issue by Tigerly** [Open-TEE/libomnishare#1]
Hello,
I'm trying to build this TA file. Should I download the android source code for compiling this TA file(libomnishare.so)? 
Would it be possible to explain a little bit more about how to develop and build my own TA and CA?

Thanks in advance!

**Comment by thomasnyman** [comment]
The libomnishare.so library contains the interface implementation the client application uses to communicate with the TA. The TA implementation can be found in https://github.com/Open-TEE/TAs/tree/master/omnishare_ta

If building for Android, libomnishare.so only requires the Android NDK, not the full Android source code.
